### PR TITLE
Use firmware's blake2s() function

### PR DESCRIPTION
**Pull request by mchack-work**
Firmware now provides a blake2s() function. Use it in rng_stream.

Still draft since we still have blake2s functions left. And need to see that everything works OK.

See https://github.com/tillitis/tillitis-key1/pull/53 for firmware changes and https://github.com/tillitis/qemu/pull/9 for qemu changes.

### CODE REVIEW

**Comment by mchack-work** [comment]
Wrote a wrapper function in libcommon that calls firmware's blake2s() and then used that in rng_stream. Now ready for review.

**Comment by quite** [comment]
Works well and looks good!

**Comment by secworks** [comment]
I have reviewed the code. It looks good to me.

**Review by secworks — COMMENTED** [review]
Looks good.

**Pull request merged**
